import pandas as pd
# import measurements
from helpers import Ingredient

class Unit(object):
	name = ''
	aliases = []

	def __init__(self, n='', a=[]):
		self.name = n
		self.aliases = a

measurements = {'volume': [ Unit('teaspoon', ['t', 'tsp']),
							Unit('tablespoon', ['T', 'tbl', 'tbs', 'tbsp']),
							Unit('fluid ounce',['fl oz']),
							Unit('cup', ['c']),
							Unit('pint', ['p', 'pt', 'fl pt']),
							Unit('quart', ['q', 'qt', 'fl qt']),
							Unit('gallon', ['g', 'gal']),
							Unit('milliliter', ['ml', 'millilitre', 'mL']),
							Unit('liter', ['l', 'L', 'litre'])],
				'mass/weight': [ Unit('pound',  ['lb', '#']),
								Unit('ounce', ['oz']),
								Unit('milligram', ['mg', 'milligramme']),
								Unit('gram', ['g', 'gramme']),
								Unit('kilogram', ['kg', 'kilogramme'])],
				'time': [ Unit('day',[]),
						Unit('hour', ['hr']),
						Unit('minute', ['min']),
						Unit('second', ['sec', 's'])]
				}

# not case sensitive
meats = [ Ingredient(name="bacon", category="protein", subcategory="meat"), 
Ingredient(name="beef", category="protein", subcategory="meat"), 
Ingredient(name="bison", category="protein", subcategory="meat"), 
Ingredient(name="blood", category="protein", subcategory="meat"), 
Ingredient(name="chicken", category="protein", subcategory="meat"),
Ingredient(name="chorizo", category="protein", subcategory="meat"), 
Ingredient(name="cornish game hen", category="protein", subcategory="meat"),
Ingredient(name="duck", category="protein", subcategory="meat"), 
Ingredient(name="foie gras", category="protein", subcategory="meat"), 
Ingredient(name="game", category="protein", subcategory="meat"), 
Ingredient(name="giblets", category="protein", subcategory="meat"), 
Ingredient(name="goat", category="protein", subcategory="meat"),
Ingredient(name="goose", category="protein", subcategory="meat"), 
Ingredient(name="guinea pig", category="protein", subcategory="meat"), 
Ingredient(name="ham", category="protein", subcategory="meat"), 
Ingredient(name="hedgehog", category="protein", subcategory="meat"), 
Ingredient(name="horse", category="protein", subcategory="meat"),
Ingredient(name="hot dog", category="protein", subcategory="meat"), 
Ingredient(name="kidney", category="protein", subcategory="meat"), 
Ingredient(name="kielbasa", category="protein", subcategory="meat"), 
Ingredient(name="lamb", category="protein", subcategory="meat"), 
Ingredient(name="liver", category="protein", subcategory="meat"),
Ingredient(name="mortadella", category="protein", subcategory="meat"), 
Ingredient(name="mutton", category="protein", subcategory="meat"),
Ingredient(name="neck sweetbread", category="protein", subcategory="meat"), 
Ingredient(name="organ meat", category="protein", subcategory="meat"),
Ingredient(name="ostrich", category="protein", subcategory="meat"), 
Ingredient(name="pancetta", category="protein", subcategory="meat"), 
Ingredient(name="pastrami", category="protein", subcategory="meat"), 
Ingredient(name="pepperoni", category="protein", subcategory="meat"), 
Ingredient(name="pork", category="protein", subcategory="meat"),
Ingredient(name="prosciutto", category="protein", subcategory="meat"), 
Ingredient(name="quail", category="protein", subcategory="meat"), 
Ingredient(name="rabbit", category="protein", subcategory="meat"), 
Ingredient(name="salami", category="protein", subcategory="meat"), 
Ingredient(name="sausage", category="protein", subcategory="meat"),
Ingredient(name="sausage casing", category="protein", subcategory="meat"), 
Ingredient(name="squirrel", category="protein", subcategory="meat"), 
Ingredient(name="stomach sweetbread", category="protein", subcategory="meat"),
Ingredient(name="sweetbread", category="protein", subcategory="meat"), 
Ingredient(name="tongue", category="protein", subcategory="meat"), 
Ingredient(name="tripe", category="protein", subcategory="meat"), 
Ingredient(name="turkey", category="protein", subcategory="meat"), 
Ingredient(name="veal", category="protein", subcategory="meat"), 
Ingredient(name="venison", category="protein", subcategory="meat"),
Ingredient(name="burger", category="protein", subcategory="meat"), 
Ingredient(name="meatballs", category="protein", subcategory="meat")]

# not case sensitive
seafood= [ Ingredient(name="salmon", category="protein", subcategory="seafood"), Ingredient(name="cod", category="protein", subcategory="seafood"), Ingredient(name="halibut", category="protein", subcategory="seafood"), Ingredient(name="mahi mahi", category="protein", subcategory="seafood"), Ingredient(name="tuna", category="protein", subcategory="seafood"), Ingredient(name="shark", category="protein", subcategory="seafood"),
			Ingredient(name="swordfish", category="protein", subcategory="seafood"), Ingredient(name="sturgeon", category="protein", subcategory="seafood"), Ingredient(name="catfish", category="protein", subcategory="seafood"), Ingredient(name="trout", category="protein", subcategory="seafood"), Ingredient(name="sardine", category="protein", subcategory="seafood"), 
			Ingredient(name="anchovy", category="protein", subcategory="seafood"), Ingredient(name="arctic char", category="protein", subcategory="seafood"), Ingredient(name="crab", category="protein", subcategory="seafood"), Ingredient(name="crayfish", category="protein", subcategory="seafood"), Ingredient(name="lobster", category="protein", subcategory="seafood"), 
			Ingredient(name="shrimp", category="protein", subcategory="seafood"), Ingredient(name="molluscs", category="protein", subcategory="seafood"), Ingredient(name="abalone", category="protein", subcategory="seafood"), Ingredient(name="clam", category="protein", subcategory="seafood"), Ingredient(name="cockle", category="protein", subcategory="seafood"), Ingredient(name="mussel", category="protein", subcategory="seafood"),
			Ingredient(name="octopus", category="protein", subcategory="seafood"), Ingredient(name="oyster", category="protein", subcategory="seafood"), Ingredient(name="pipi", category="protein", subcategory="seafood"), Ingredient(name="snail", category="protein", subcategory="seafood"), Ingredient(name="conch", category="protein", subcategory="seafood"), Ingredient(name="whelk", category="protein", subcategory="seafood"),
			Ingredient(name="winkle", category="protein", subcategory="seafood"), Ingredient(name="squid", category="protein", subcategory="seafood"), Ingredient(name="calamari", category="protein", subcategory="seafood"), Ingredient(name="scallop", category="protein", subcategory="seafood"), Ingredient(name="caviar", category="protein", subcategory="seafood"), Ingredient(name="uni", category="protein", subcategory="seafood"),
			Ingredient(name="sea cucumber", category="protein", subcategory="seafood"), Ingredient(name="hagfish", category="protein", subcategory="seafood"), Ingredient(name="tuna", category="protein", subcategory="seafood"), Ingredient(name="ikura", category="protein", subcategory="seafood")]

dairy = [
		Ingredient(name="butter", category="protein", subcategory= "dairy"),
		Ingredient(name="ghee", category="protein", subcategory= "dairy"),
		Ingredient(name="buttermilk", category="protein", subcategory= "dairy"),
		Ingredient(name="cheese", category="protein", subcategory= "dairy"),
		Ingredient(name="cream", category="protein", subcategory= "dairy"),
		Ingredient(name="sour cream", category="protein", subcategory= "dairy"),
		Ingredient(name="whipped cream", category="protein", subcategory= "dairy"),
		Ingredient(name="milk", category="protein", subcategory= "dairy"),
		Ingredient(name="condensed milk", category="protein", subcategory= "dairy"),
		Ingredient(name="yogurt", category="protein", subcategory= "dairy"),
		Ingredient(name="lassi", category="protein", subcategory= "dairy"),
		Ingredient(name="bohrani", category="protein", subcategory= "dairy"),
		Ingredient(name="kefir", category="protein", subcategory= "dairy"),
		Ingredient(name="egg", category="protein", subcategory= "dairy"),
		Ingredient(name="egg white", category="protein", subcategory= "dairy"),
		Ingredient(name="egg yolk", category="protein", subcategory= "dairy")]

#veg_proteins
veg_proteins = [ Ingredient(name="tofu", category="protein", subcategory="veg_protein"), Ingredient(name="tempeh", category="protein", subcategory="veg_protein"), Ingredient(name="seitan", category="protein", subcategory="veg_protein"), Ingredient(name="jackfruit", category="protein", subcategory="veg_protein"), Ingredient(name="lentils", category="protein", subcategory="veg_protein"), Ingredient(name="beans", category="protein", subcategory="veg_protein"),
				Ingredient(name="legumes", category="protein", subcategory="veg_protein"), Ingredient(name="texturized vegetable protein (TVP)", category="protein", subcategory="veg_protein"),#tvp
				Ingredient(name="chickpeas", category="protein", subcategory="veg_protein"), Ingredient(name="falafel", category="protein", subcategory="veg_protein"), Ingredient(name="nuts", category="protein", subcategory="veg_protein"), Ingredient(name="soy", category="protein", subcategory="veg_protein"), Ingredient(name="vegetarian bacon", category="protein", subcategory="veg_protein"), Ingredient(name="veggie burger", category="protein", subcategory="veg_protein"),
				Ingredient(name="tofurkey", category="protein", subcategory="veg_protein"), Ingredient(name="veggie dog", category="protein", subcategory="veg_protein"), Ingredient(name="quinoa", category="protein", subcategory="veg_protein"), Ingredient(name='chik\'n', category="protein", subcategory="veg_protein")]

meat_subs = { Ingredient(name='hamburger', category="protein", subcategory="meat"): [Ingredient(name='veggie burger', category="protein", subcategory="veg_protein"), Ingredient(name='black bean burger', category="protein", subcategory="veg_protein")],
				Ingredient(name='meatball', category="protein", subcategory="meat"): [Ingredient(name='veggie meatballs', category="protein", subcategory="veg_protein")],
				Ingredient(name='hot dog', category="protein", subcategory="meat"): [Ingredient(name='veggie dog', category="protein", subcategory="veg_protein")],
				Ingredient(name='sausage', category="protein", subcategory="meat"): [Ingredient(name='veggie sausage', category="protein", subcategory="veg_protein"), Ingredient(name='tempeh', category="protein", subcategory="veg_protein")],
				Ingredient(name='chicken', category="protein", subcategory="meat"): [Ingredient(name='chik\'n', category="protein", subcategory="veg_protein"), Ingredient(name='tofu', category="protein", subcategory="veg_protein"), Ingredient(name='seitan', category="protein", subcategory="veg_protein")],
				Ingredient(name='default', category="protein", subcategory="meat"): [Ingredient(name='tofu', category="protein", subcategory="veg_protein"), Ingredient(name="texturized vegetable protein (TVP)", category="protein", subcategory="veg_protein")],
				Ingredient(name='pork', category="protein", subcategory="meat"): [Ingredient(name='seitan', category="protein", subcategory="veg_protein")],
				Ingredient(name='turkey', category="protein", subcategory="meat"): [Ingredient(name='tofurkey', category="protein", subcategory="veg_protein")],
				Ingredient(name='beef', category="protein", subcategory="meat"): [Ingredient(name='tofu', category="protein", subcategory="veg_protein"), Ingredient(name='seitan', category="protein", subcategory="veg_protein")],
				Ingredient(name='fish', category="protein", subcategory="meat"): [Ingredient(name='tofu', category="protein", subcategory="veg_protein")],
				Ingredient(name='chorizo', category="protein", subcategory="meat"): [Ingredient(name='beans', category="protein", subcategory="veg_protein")]
			}

proteins = meats + seafood + veg_proteins + dairy

# REGEX: get before new line (.*)(\n)
# replace: Ingredient(name="\1", category="healthy", subcategory="vegetable"),\2

vegetables = [Ingredient(name="alfalfa sprouts", category="healthy", subcategory="vegetable"),
Ingredient(name="anise", category="healthy", subcategory="vegetable"),
Ingredient(name="artichoke", category="healthy", subcategory="vegetable"),
Ingredient(name="arugula", category="healthy", subcategory="vegetable"),
Ingredient(name="asparagus", category="healthy", subcategory="vegetable"),
Ingredient(name="aubergine", category="healthy", subcategory="vegetable"),
Ingredient(name="avocado", category="healthy", subcategory="vegetable"),
Ingredient(name="brassica", category="healthy", subcategory="vegetable"),
Ingredient(name="broccoflower", category="healthy", subcategory="vegetable"),
Ingredient(name="broccoli", category="healthy", subcategory="vegetable"),
Ingredient(name="broccolini", category="healthy", subcategory="vegetable"),
Ingredient(name="broccoli rabe", category="healthy", subcategory="vegetable"),
Ingredient(name="brussels sprout", category="healthy", subcategory="vegetable"),
Ingredient(name="cabbage", category="healthy", subcategory="vegetable"),
Ingredient(name="cauliflower", category="healthy", subcategory="vegetable"),
Ingredient(name="romanesco broccoli", category="healthy", subcategory="vegetable"),
Ingredient(name="yu choy", category="healthy", subcategory="vegetable"),
Ingredient(name="choy sum", category="healthy", subcategory="vegetable"),
Ingredient(name="bok choy", category="healthy", subcategory="vegetable"),
Ingredient(name="nappa cabbage", category="healthy", subcategory="vegetable"),
Ingredient(name="collard green", category="healthy", subcategory="vegetable"),
Ingredient(name="kohlrabi", category="healthy", subcategory="vegetable"),
Ingredient(name="breadfruit", category="healthy", subcategory="vegetable"),
Ingredient(name="cactus pad", category="healthy", subcategory="vegetable"),
Ingredient(name="calabrese", category="healthy", subcategory="vegetable"),
Ingredient(name="celery", category="healthy", subcategory="vegetable"),
Ingredient(name="chard", category="healthy", subcategory="vegetable"),
Ingredient(name="chicory", category="healthy", subcategory="vegetable"),
Ingredient(name="cucumber", category="healthy", subcategory="vegetable"),
Ingredient(name="eggplant", category="healthy", subcategory="vegetable"),
Ingredient(name="endive", category="healthy", subcategory="vegetable"),
Ingredient(name="edible cactus", category="healthy", subcategory="vegetable"),
Ingredient(name="fennel", category="healthy", subcategory="vegetable"),
Ingredient(name="fiddlehead", category="healthy", subcategory="vegetable"),
Ingredient(name="frisee", category="healthy", subcategory="vegetable"),
Ingredient(name="hop shoot", category="healthy", subcategory="vegetable"),
Ingredient(name="kale", category="healthy", subcategory="vegetable"),
Ingredient(name="kangkung", category="healthy", subcategory="vegetable"),
Ingredient(name="soybean", category="healthy", subcategory="vegetable"),
Ingredient(name="garlic", category="healthy", subcategory="vegetable"),
Ingredient(name="winter leek", category="healthy", subcategory="vegetable"),
Ingredient(name="legume", category="healthy", subcategory="vegetable"),
Ingredient(name="azuki bean", category="healthy", subcategory="vegetable"),
Ingredient(name="beansprout", category="healthy", subcategory="vegetable"),
Ingredient(name="black bean", category="healthy", subcategory="vegetable"),
Ingredient(name="black-eyed pea", category="healthy", subcategory="vegetable"),
Ingredient(name="borlotti bean", category="healthy", subcategory="vegetable"),
Ingredient(name="broad bean", category="healthy", subcategory="vegetable"),
Ingredient(name="chickpea", category="healthy", subcategory="vegetable"),
Ingredient(name="green bean", category="healthy", subcategory="vegetable"),
Ingredient(name="red kidney bean", category="healthy", subcategory="vegetable"),
Ingredient(name="lentil", category="healthy", subcategory="vegetable"),
Ingredient(name="lima bean", category="healthy", subcategory="vegetable"),
Ingredient(name="mung bean", category="healthy", subcategory="vegetable"),
Ingredient(name="navy bean", category="healthy", subcategory="vegetable"),
Ingredient(name="runner bean", category="healthy", subcategory="vegetable"),
Ingredient(name="soybean", category="healthy", subcategory="vegetable"),
Ingredient(name="pea", category="healthy", subcategory="vegetable"),
Ingredient(name="snap pea", category="healthy", subcategory="vegetable"),
Ingredient(name="lemongrass", category="healthy", subcategory="vegetable"),
Ingredient(name="lettuce Lactuca sativa", category="healthy", subcategory="vegetable"),
Ingredient(name="corn", category="healthy", subcategory="vegetable"),
Ingredient(name="mangetout", category="healthy", subcategory="vegetable"),
Ingredient(name="mustard green", category="healthy", subcategory="vegetable"),
Ingredient(name="nettles", category="healthy", subcategory="vegetable"),
Ingredient(name="new zealand spinach", category="healthy", subcategory="vegetable"),
Ingredient(name="nori", category="healthy", subcategory="vegetable"),
Ingredient(name="okra", category="healthy", subcategory="vegetable"),
Ingredient(name="onion family", category="healthy", subcategory="vegetable"),
Ingredient(name="chive", category="healthy", subcategory="vegetable"),
Ingredient(name="garlic", category="healthy", subcategory="vegetable"),
Ingredient(name="onion", category="healthy", subcategory="vegetable"),
Ingredient(name="shallot", category="healthy", subcategory="vegetable"),
Ingredient(name="scallion ", category="healthy", subcategory="vegetable"),
Ingredient(name="shallot", category="healthy", subcategory="vegetable"),
Ingredient(name="parsley", category="healthy", subcategory="vegetable"),
Ingredient(name="daikon", category="healthy", subcategory="vegetable"),
Ingredient(name="potatoes", category="healthy", subcategory="vegetable"),
Ingredient(name="pepper", category="healthy", subcategory="vegetable"),
Ingredient(name="bell pepper", category="healthy", subcategory="vegetable"),
Ingredient(name="chili pepper", category="healthy", subcategory="vegetable"),
Ingredient(name="radicchio", category="healthy", subcategory="vegetable"),
Ingredient(name="rhubarb", category="healthy", subcategory="vegetable"),
Ingredient(name="root vegetable", category="healthy", subcategory="vegetable"),
Ingredient(name="beet", category="healthy", subcategory="vegetable"),
Ingredient(name="carrot", category="healthy", subcategory="vegetable"),
Ingredient(name="cassava", category="healthy", subcategory="vegetable"),
Ingredient(name="celeriac", category="healthy", subcategory="vegetable"),
Ingredient(name="ginger", category="healthy", subcategory="vegetable"),
Ingredient(name="sunchoke ", category="healthy", subcategory="vegetable"),
Ingredient(name="jicama", category="healthy", subcategory="vegetable"),
Ingredient(name="parsnip", category="healthy", subcategory="vegetable"),
Ingredient(name="potato", category="healthy", subcategory="vegetable"),
Ingredient(name="radish", category="healthy", subcategory="vegetable"),
Ingredient(name="skirret", category="healthy", subcategory="vegetable"),
Ingredient(name="rutabaga ", category="healthy", subcategory="vegetable"),
Ingredient(name="sweet potato ", category="healthy", subcategory="vegetable"),
Ingredient(name="taro root", category="healthy", subcategory="vegetable"),
Ingredient(name="turnip", category="healthy", subcategory="vegetable"),
Ingredient(name="wasabi", category="healthy", subcategory="vegetable"),
Ingredient(name="water chestnut", category="healthy", subcategory="vegetable"),
Ingredient(name="white radish", category="healthy", subcategory="vegetable"),
Ingredient(name="yam", category="healthy", subcategory="vegetable"),
Ingredient(name="samphire", category="healthy", subcategory="vegetable"),
Ingredient(name="silverbeet", category="healthy", subcategory="vegetable"),
Ingredient(name="snap pea", category="healthy", subcategory="vegetable"),
Ingredient(name="spinach", category="healthy", subcategory="vegetable"),
Ingredient(name="squash family", category="healthy", subcategory="vegetable"),
Ingredient(name="acorn squash", category="healthy", subcategory="vegetable"),
Ingredient(name="bitter melon", category="healthy", subcategory="vegetable"),
Ingredient(name="butternut squash", category="healthy", subcategory="vegetable"),
Ingredient(name="calabaza", category="healthy", subcategory="vegetable"),
Ingredient(name="chayote", category="healthy", subcategory="vegetable"),
Ingredient(name="cucumber", category="healthy", subcategory="vegetable"),
Ingredient(name="gem squash", category="healthy", subcategory="vegetable"),
Ingredient(name="patty pan squash", category="healthy", subcategory="vegetable"),
Ingredient(name="pumpkin", category="healthy", subcategory="vegetable"),
Ingredient(name="spaghetti squash", category="healthy", subcategory="vegetable"),
Ingredient(name="zucchini", category="healthy", subcategory="vegetable"),
Ingredient(name="tomato", category="healthy", subcategory="vegetable"),
Ingredient(name="tat soi", category="healthy", subcategory="vegetable"),
Ingredient(name="tomatillo", category="healthy", subcategory="vegetable"),
Ingredient(name="tomato", category="healthy", subcategory="vegetable"),
Ingredient(name="watercress", category="healthy", subcategory="vegetable")]


tools = ["baking sheet","blender","bowl","box grater","brush","can opener","cast iron skillet",
		"colander","cutting board","double boiler","dutch oven","foil","food processer ","fork","frying pan",
		"funnel","garlic press","grill","hand mixer","knife","ladel","mandoline","measuring cup","microplane", 
		"mortar","paper towel","parchment paper","paring knife","peeler","pesltle","plastic wrap","plate","pot",
		"rack",'ramekin',"roasting pan","rolling pin","saucepan","sheet pan","sieve","skewer","skillet","smoker",
		"spatula","spoon","stand mixer","stock pot","thermometer","timer","tongs","twine","whisk", "sifter", "strainer", "mallet"]

primary_methods = ["bake","barbeque","boil","broil","braise","carmelize","flambe","fry","grill",
					"parbake","parboil","poach","roast","sear", "smoke","steam","saute", "sauté" "simmer",
					"stir fry","stew","sweat","toast", "baste", "melt", "reduce", "render", "temper", "freeze", "clarify"]

secondary_methods = ["arange","add","heat","brown","beat","blache","heat","cover","chop","combine",
					"crush","cube","cut","deglaze","dice","form", "fold","grind","julienne" ,"knead","mince","mix",
					"pound","preheat","pour","roll","rub","season","shredd","skewer","slice","stir","transfer","tenderize","whisk",
					"spoon", "drain", "sprinkle", "top", "layer", "lay", "place", "set", "strain", "line", "oil", "butter", "prepare"
					"refrigerate", "arrange", "turn", "flip", "brush", "galze", "dip" , 
					"spread", "press", "coat", "pat", "save", "reserve","put", "return", "scrape", "peel", "rinsed" "remove", "repeat", "allow", "rest", "toss", "distribute", "wash", "fill",
					"mash", "smash", "blend", "cool", "store", "cream", "drop", "dissolve"]

units = ["bag","teaspoon","tablespoon","ounce","clove","cup","pint","quart","gallon",
		"milliliter","liter","pound","gram","milligram","kilogram","pinch", "pinches", "handful","head",
		"loaf","loaves","can","package", "pack","bunch","bushel","T","tsp",'t',"tbl","tbsp",'tbs','c','p','gal','g']

preparations = ["chopped","shredded","ground","crushed","sliced","cooked","pureed",
				"peeled","smoked","minced","rinsed","trimmed","uncooked","rolled","pounded","cut","diced", "halved", "melted", "frozen", "clarified"]

"""
method_tools = {
	"bake" : "oven",
	"barbeque": "barbeque",
	"boil": "pot",
	"broil": "oven",
	"braise": "pot",
	"carmelize" : "pan",
	"flambe": "man",
	"fry": "pan",
	"parkbake": "oven",
	"parboil": "pot",
	"poach": "pot",
	"roast": "oven",
	"sear": "pan",
	"smoke": "smoker",
	"steam": "pot",
	"saute": "pan",
	"sauté" : "pan",
	"simmer": "pot",
	"stir fry": "pan",
	"stew": "pot",
	"sweat": "pan",
	"toast": "toaster",

}
"""